<div class="alert alert-info">
    <button class="close" data-dismiss="alert" type="button">x</button>
    <h2><?php echo $this->event->getTitle() ?> &mdash; Gästeliste</h2>
    <ul class="inline">
        <li>Gäste: <?php echo count($this->guests) ?></li>
        <li>Zusagen: <?php echo count($this->guests) ?></li>
        <li>Absagen: <?php echo count($this->guests) ?></li>
        <li>Offen: <?php echo count($this->guests) ?></li>
    </ul>
</div>
<?php echo $this->HtmlTable($this->guests); ?>
<?php // \Zend\Debug\Debug::dump($this->guests); ?>
<?php echo $this->paginationControl($this->guests, 'Sliding', array('partial/paginator.phtml', 'Event'), array('route' => 'events/action', 'id' => $this->event->getId())); ?>
